apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mbclaw

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app: mbclaw-lite
  app.kubernetes.io/part-of: mbclaw

images:
- name: mbclaw-lite
  newTag: latest
